apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-deployment-cache
  labels:
    app: netology-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netology-cache
  template:
    metadata:
      labels:
        app: netology-cache
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8090"
        ports:
        - containerPort: 8090

